### ISSUE TITLE
Make CircuitParameters#init public

### ISSUE THREAD

**Issue by bduisenov** [IBM-Swift/SwiftyRequest#16]
Hi, it seems that `CircuitParameters#init` should be public as it is not possible to instantiate it.

**Comment by sandmman** [comment]
@bduisenov Oh thanks for pointing that out! I just pushed up the fix

**Comment by ianpartridge** [comment]
Fixed in https://github.com/IBM-Swift/SwiftyRequest/commit/5b64cccbc1dd986632c4ae22be409fb095c15c75
