### ISSUE TITLE
Certificate Pinning

### ISSUE THREAD

**Issue by steamonimo** [IBM-Swift/SwiftyRequest#19]
I need to verify my HTTPS requests via certificate pinning. Is there a way to verify the hash of the server certificate I am connecting to?

**Comment by ShihabMehboob** [comment]
This has now been created on the following branch: https://github.com/IBM-Swift/SwiftyRequest/tree/cert_pinning

A PR will be opened for it.

**Comment by steamonimo** [comment]
Thanks for this branch but I need a solution for macOS and Linux. My main problem is that the URLSessionDelegate in module Security is not available on Swift 4.0.3 for Linux. It seems that Swift for Linux is just one big construction site for years to come.

**Comment by ianpartridge** [comment]
Yes I'm afraid this functionality is not going to be available on Linux for the foreseeable future.
