### ISSUE TITLE
How to check if .failure only?

### ISSUE THREAD

**Issue by sergeydi** [IBM-Swift/SwiftyRequest#21]
Hi
In the example you check both .success and .failure result of request.responseString(). But how to check only if result is .failure?

**Comment by ShihabMehboob** [comment]
@sergeydi Hey, we currently check different cases using:

```
switch response.result {
    case .success(let result):
        print("Success")
    case .failure(let error):
        print("Failure")
    }
```

However, you could choose to ignore the success part and just insert your logic within the failure case if that's all you wanted. Or you could use an if check to see something like:

```
if response.result == .failure {
print("Failure")
}
```

**Comment by ShihabMehboob** [comment]
@sergeydi Apologies, was thinking of something else. If you use the following piece of code, you should be able to do it with just a failure check:

```
switch response.result {
            case .failure(let error):
                print("Failed")
            default: ()
            }
```

**Comment by sergeydi** [comment]
It works, thank you :)
