### ISSUE TITLE
Failure on Linux - Foundation.URLError(_nsError: The operation could not be completed))

### ISSUE THREAD

**Issue by rashid-ahmad** [IBM-Swift/SwiftyRequest#22]
Hi 

I am running into an issue executing on Linux (works fine on macOS).

Here is the code (taken heavily from examples)>

```
import Foundation
import SwiftyRequest
 

let headers = [
  "Accept": "application/json",
  "Content-Type": "application/json",
]

func getData() -> Data {
  let parameters = [
    "address":"server.node1.COM",
    "info":"info1"
    ] as [String : String]
  guard let data = try? JSONSerialization.data(withJSONObject: parameters, options: []) else {
    print("Could not encode json")
    return Data()
  }
  return data
}

let request = RestRequest(method: .post, url: "https://server.node1.COM/action")
request.headerParameters = headers
request.messageBody = getData()
request.responseString(responseToError: nil) { response in
  print (response.result)
  switch response.result {
  case .success(let token):
    print ("success")
  case .failure(let error):
    print ("failure")
    print (error.localizedDescription)
  }  
  print (response.request)
  print (response.response)
  print (response.result)
  print (response.data)
}
RunLoop.main.run()
```

On macOS this happily returns json, but on Linux the error message is 

`failure(Foundation.URLError(_nsError: The operation could not be completed))`

Appreciate any insight into this.

**Comment by ShihabMehboob** [comment]
It appears that this is related to a known issue on Swift: https://bugs.swift.org/browse/SR-6788

**Comment by ShihabMehboob** [comment]
@rashid-ahmad Hey, thank you for alerting us about the issue. Upon further investigation, it appears that this does indeed seem to work fine on both macOS as well as Linux (at least on my end). 

To replicate your issue, I created a simple test using your above code example within SwiftyRequest and ran it in a local Linux Docker image. Using the example URL provided within the `SwiftyRequestTests.swift` class (wunderground api), it worked fine and returned JSON for both macOS and Linux (certain elements were also isolated into Linux #if blocks to see whether this may have been an environment error on my end, but confirmed that there was no error). However, trying the same thing with your address and URL returned a self-signed certificate error. Could it be that the URL and host you're using could be faulty and not set up correctly?

You could also try out the same thing by adding your code block to the test cases within `SwiftyRequestTests.swift`, trying out the URL and address with yours as well as with the stock one provided within the test class (`http://api.wunderground.com/api/\(apiKey)/conditions/q/CA/San_Francisco.json`), and running the following command from within the project directory to run it locally on Docker (assuming you have it installed): `docker run --rm -v "$(pwd):/pkg" -w "/pkg" swift:latest /bin/bash -c "swift test --build-path ./.build/linux"`. Could you also please ensure that you have the latest SwiftyRequest installed too. I'd love to know if you're still running into this issue.

**Comment by ianpartridge** [comment]
Closing as no response - please do reopen if needed!
