### ISSUE TITLE
Repeated use of RestRequest leaks memory (via URLSession and URLSessionConfiguration)

### ISSUE THREAD

**Issue by mman** [IBM-Swift/SwiftyRequest#24]
I have created a simple program that demonstrates how repeated use of ``RestRequest.response()`` leaks memory quite fast.

Please see here: https://github.com/mman/leaky-swifty-request

The leak is happening on both Mac and Linux and seems to be caused by the fact that ``URLSession(configuration: URLSessionConfiguration)`` itself is leaking internally due to retain cycle.

<img width="1282" alt="screen shot 2018-05-02 at 22 22 14" src="https://user-images.githubusercontent.com/249814/39548150-f20a04cc-4e59-11e8-9005-46c7b931f9e7.png">

The workaround at least for me seems to be to use ``URLSession.shared`` by default. I'll send PR in the next few days if confirmed to be working stable.

This is the problematic line https://github.com/IBM-Swift/SwiftyRequest/blob/master/Sources/SwiftyRequest/RestRequest.swift#L30.

**Comment by schlingding** [comment]
May be related to #59.

**Comment by djones6** [comment]
A fix has been delivered in [SwiftyRequest 2.0.6](https://github.com/IBM-Swift/SwiftyRequest/releases/tag/2.0.6) - please try this version at your convenience.
