### ISSUE TITLE
Make Result Equatable

### ISSUE THREAD

**Issue by svanimpe** [IBM-Swift/SwiftyRequest#27]
While using SwiftyRequest for end-to-end testing, I noticed Result isn't Equatable, so I've added the following extension:

```swift
extension Result: Equatable where T: Equatable {
    
    public static func ==(lhs: Result, rhs: Result) -> Bool {
        switch (lhs, rhs) {
        case (.success(let left), .success(let right)) where left == right:
            return true
        case (.failure, .failure):
            return true
        default:
            return false
        }
    }
}
```

Could this be added to SwiftyRequest itself, or do you see any problems with this?

**Comment by ianpartridge** [comment]
I can't see a problem with adding this.

**Comment by ianpartridge** [comment]
Hi @ShihabMehboob can you take a look at adding this?

**Comment by ShihabMehboob** [comment]
PR for this issue: https://github.com/IBM-Swift/SwiftyRequest/pull/29

**Comment by ianpartridge** [comment]
Merged.
