### ISSUE TITLE
2.0.0 version not building for iOS

### ISSUE THREAD

**Issue by bikram990** [IBM-Swift/SwiftyRequest#36]
with 2.0.0 version _SecIdentityCreateWithCertificate_ API was added in **RestRequest.swift**. This is only available in macOS and therefore the project doesn't build for iOS.

version 1.1.3 builds fine on iOS

**Comment by ianpartridge** [comment]
Oops, thanks for letting us know. We'll fix up the `#if`s :)

**Comment by ianpartridge** [comment]
Fixed in #37 and released as `2.0.1`. Thanks!
