### ISSUE TITLE
problem in checking secure connection

### ISSUE THREAD

**Issue by TheM4hd1** [IBM-Swift/SwiftyRequest#45]
https://github.com/IBM-Swift/SwiftyRequest/blob/2bf11cdf775da7c39a8658100a8c66f12d759109/Sources/SwiftyRequest/RestRequest.swift#L185

It seems there's a mistake in checking ```https```, any url that contains ```https``` will marked as secure even if a connection is not secure.

Ex. ```http://some-site-without-ssl/https-configuration.html```

**Comment by nethraravindran** [comment]
Tagged https://github.com/IBM-Swift/SwiftyRequest/releases/tag/2.0.3
Closing this issue
