### ISSUE TITLE
[Feature request] easy way to access RestResponse cookies

### ISSUE THREAD

**Issue by TaborKelly** [IBM-Swift/SwiftyRequest#64]
It would be a lot easier for clients to have some sort of collection of cookies encapsulated by `RestResponse` than of having to fish them out of the `HTTPURLResponse` headers on their own.

**Comment by ianpartridge** [comment]
Yes I don't see any problem with adding such a feature.

**Comment by djones6** [comment]
This was merged in #68 and is tagged in `2.2.0`
